name: Dev Database
description: Dev Database

inputs:
  DATABASE_URL:
    description: 'Database URL'
    required: true
  DIRECT_URL:
    description: 'Direct URL'
    required: true
  TEST_USER_ID:
    description: 'Test user ID'
    required: true
  TEST_USER_NAME:
    description: 'Test user name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Seed database
      shell: bash
      run: pnpm prisma:reset
      env:
        DATABASE_URL: ${{ inputs.DATABASE_URL }}
        DIRECT_URL: ${{ inputs.DIRECT_URL }}
        TEST_USER_ID: ${{ inputs.TEST_USER_ID }}
        TEST_USER_NAME: ${{ inputs.TEST_USER_NAME }}
