export const MINUTE_MS = 60_000;
export const HOUR_MS = 60 * MINUTE_MS;
export const DAY_MS = 24 * HOUR_MS;

export const MAGIC_LINK_DEFAULT_TTL_MS = DAY_MS;
export const STAFF_SESSION_TTL_MS = 14 * DAY_MS;
export const LINE_LINK_TOKEN_TTL_MS = 72 * HOUR_MS;
export const LEGAL_CONSENT_TOKEN_TTL_MS = 30 * DAY_MS;
export const RATE_LIMIT_RETRY_FALLBACK_MS = MINUTE_MS;
export const RESEND_EMAIL_SEND_INTERVAL_MS = 600;
export const RESEND_EMAIL_SEND_TIMEOUT_MS = 10_000;
export const RESEND_RETRY_DELAY_PADDING_MS = 250;
export const SUBMIT_ACTION_GUARD_WINDOW_MS = MINUTE_MS;
export const NOTIFICATION_OUTBOX_WORKER_BATCH_SIZE = 10;
export const NOTIFICATION_OUTBOX_ENQUEUE_DELAY_MS = 1_000;
export const NOTIFICATION_OUTBOX_MAX_ATTEMPTS = 5;
export const NOTIFICATION_OUTBOX_RETRY_BASE_MS = MINUTE_MS;
export const NOTIFICATION_OUTBOX_RETRY_MAX_MS = HOUR_MS;
export const NOTIFICATION_DELIVERY_EVENT_RETENTION_MS = 90 * DAY_MS;
export const NOTIFICATION_DELIVERY_EVENT_PRUNE_BATCH_SIZE = 100;
export const NOTIFICATION_FAILURE_INBOX_RETENTION_MS = 30 * DAY_MS;
export const NOTIFICATION_FAILURE_INBOX_EXPIRE_BATCH_SIZE = 100;

export const SHIFT_BOARD_STAFF_LIMIT = 200;
export const DASHBOARD_RESPONSE_COUNT_LIMIT = 1000;
export const DASHBOARD_CURRENT_RECRUITMENT_SCAN_LIMIT = 500;
export const DASHBOARD_RECRUITMENT_CANDIDATE_GROUP_LIMIT = 100;
export const SHIFT_BOARD_SHIFT_REQUEST_LIMIT = 2000;
export const SHIFT_ASSIGNMENT_LIMIT = 2000;
export const RECRUITMENT_DUPLICATE_SCAN_LIMIT = 500;
export const OPEN_RECRUITMENT_NOTIFICATION_LIMIT = 50;
export const SHIFT_REQUESTS_PER_SUBMISSION_LIMIT = 31;
export const SHIFT_BOARD_TIME_UNIT_MINUTES = 30;
export const STAFF_REGISTRATION_PENDING_LIMIT = 20;
export const STAFF_REGISTRATION_DAILY_DIGEST_PENDING_PAGE_SIZE = 100;
export const STAFF_REGISTRATION_DAILY_DIGEST_MANAGER_LIMIT = 20;
export const SHOP_NAME_MAX_LENGTH = 80;
export const PERSON_NAME_MAX_LENGTH = 80;
export const SHIFT_TYPE_NAME_MAX_LENGTH = 30;
export const EMAIL_MAX_LENGTH = 254;
export const STAFF_ADD_ENTRIES_MAX = 50;
export const RECRUITMENT_PERIOD_DAYS_MAX = 62;
export const FEATURE_REQUEST_COMMENT_MAX_LENGTH = 200;
export const FEATURE_REQUEST_REQUEST_ID_MAX_LENGTH = 64;
export const FEATURE_REQUEST_LIST_LIMIT = 50;
export const CONTACT_NAME_MAX_LENGTH = 100;
export const CONTACT_ORGANIZATION_MAX_LENGTH = 100;
export const CONTACT_MESSAGE_MAX_LENGTH = 2000;
export const CONTACT_TURNSTILE_TOKEN_MAX_LENGTH = 2048;
export const CONTACT_HTTP_BODY_MAX_BYTES = 16 * 1024;
// 承認依頼digestの通知期間。最新依頼からこの期間を過ぎたら通知しない（日次cronで最大3回）
export const STAFF_REGISTRATION_DIGEST_WINDOW_MS = 3 * DAY_MS;

// シフト確定催促リマインダーで一度に通知するマネージャーの上限
export const SHIFT_CONFIRMATION_REMINDER_MANAGER_LIMIT = 20;

// 初回店舗登録後の本番募集リマインダーで一度に通知するマネージャーの上限
export const SHOP_ACTIVATION_REMINDER_MANAGER_LIMIT = 20;

// 失敗通知リマインダーの通知期間。最新の失敗からこの期間を過ぎたら通知しない（日次cronで最大3回）
export const NOTIFICATION_FAILURE_REMINDER_WINDOW_MS = 3 * DAY_MS;
export const NOTIFICATION_FAILURE_REMINDER_PENDING_PAGE_SIZE = 100;
export const NOTIFICATION_FAILURE_REMINDER_MANAGER_LIMIT = 20;

// 分析KPI日次集計のページサイズ。イベント走査は1行=1読み取りなので大きめでよい
export const ANALYTICS_AGGREGATION_PAGE_SIZE = 100;
// 店舗スナップショット集計は店舗ごとにスタッフ・LINE連携・募集を読むため小さめにする
export const ANALYTICS_SHOP_SNAPSHOT_PAGE_SIZE = 10;
// 分析internalQueryが一度に返す時系列行数の上限（約2年分）
export const ANALYTICS_QUERY_RANGE_LIMIT = 731;
// 店舗ステージ判定で1店舗あたり走査する募集・提出統計・通知失敗の上限
export const ANALYTICS_SHOP_STAGE_SCAN_LIMIT = 200;

export const DEFAULT_POSITION_NAME = "シフト";
export const DEFAULT_POSITION_COLOR = "#3b82f6";
