export const MINUTE_MS = 60_000;
export const HOUR_MS = 60 * MINUTE_MS;
export const DAY_MS = 24 * HOUR_MS;

export const MAGIC_LINK_DEFAULT_TTL_MS = DAY_MS;
export const STAFF_SESSION_TTL_MS = 14 * DAY_MS;
export const LINE_LINK_TOKEN_TTL_MS = 72 * HOUR_MS;
export const LEGAL_CONSENT_TOKEN_TTL_MS = 30 * DAY_MS;
export const RATE_LIMIT_RETRY_FALLBACK_MS = MINUTE_MS;
export const RESEND_EMAIL_SEND_INTERVAL_MS = 600;
export const RESEND_EMAIL_SEND_TIMEOUT_MS = 10_000;
export const RESEND_RETRY_DELAY_PADDING_MS = 250;
export const SUBMIT_ACTION_GUARD_WINDOW_MS = MINUTE_MS;
export const NOTIFICATION_OUTBOX_WORKER_BATCH_SIZE = 10;
export const NOTIFICATION_OUTBOX_MAX_ATTEMPTS = 5;
export const NOTIFICATION_OUTBOX_RETRY_BASE_MS = MINUTE_MS;
export const NOTIFICATION_OUTBOX_RETRY_MAX_MS = HOUR_MS;
export const NOTIFICATION_OUTBOX_SHOP_ACTIVE_LIMIT = 500;

export const SHIFT_BOARD_STAFF_LIMIT = 200;
export const DASHBOARD_RESPONSE_COUNT_LIMIT = 1000;
export const SHIFT_BOARD_SHIFT_REQUEST_LIMIT = 2000;
export const SHIFT_ASSIGNMENT_LIMIT = 2000;
export const RECRUITMENT_DUPLICATE_SCAN_LIMIT = 500;
export const OPEN_RECRUITMENT_NOTIFICATION_LIMIT = 50;
export const SHIFT_REQUESTS_PER_SUBMISSION_LIMIT = 31;
export const SHIFT_BOARD_TIME_UNIT_MINUTES = 30;
export const STAFF_REGISTRATION_PENDING_LIMIT = 20;
export const STAFF_REGISTRATION_DAILY_DIGEST_PENDING_PAGE_SIZE = 100;
export const STAFF_REGISTRATION_DAILY_DIGEST_MANAGER_LIMIT = 20;
// 承認依頼digestの通知期間。最新依頼からこの期間を過ぎたら通知しない（日次cronで最大3回）
export const STAFF_REGISTRATION_DIGEST_WINDOW_MS = 3 * DAY_MS;

export const DEFAULT_POSITION_NAME = "シフト";
export const DEFAULT_POSITION_COLOR = "#3b82f6";
