/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _lib_activeShop from "../_lib/activeShop.js";
import type * as _lib_auditCorrelation from "../_lib/auditCorrelation.js";
import type * as _lib_config from "../_lib/config.js";
import type * as _lib_dashboardUrl from "../_lib/dashboardUrl.js";
import type * as _lib_dateFormat from "../_lib/dateFormat.js";
import type * as _lib_emailFormat from "../_lib/emailFormat.js";
import type * as _lib_functions from "../_lib/functions.js";
import type * as _lib_httpBody from "../_lib/httpBody.js";
import type * as _lib_lineClient from "../_lib/lineClient.js";
import type * as _lib_lineCta from "../_lib/lineCta.js";
import type * as _lib_lineSignature from "../_lib/lineSignature.js";
import type * as _lib_lineUrl from "../_lib/lineUrl.js";
import type * as _lib_notification from "../_lib/notification.js";
import type * as _lib_notificationDelivery from "../_lib/notificationDelivery.js";
import type * as _lib_notificationDeliveryQueries from "../_lib/notificationDeliveryQueries.js";
import type * as _lib_previousWeeklyPattern from "../_lib/previousWeeklyPattern.js";
import type * as _lib_rateLimits from "../_lib/rateLimits.js";
import type * as _lib_resend from "../_lib/resend.js";
import type * as _lib_resendWebhookSignature from "../_lib/resendWebhookSignature.js";
import type * as _lib_shopManagerRecipients from "../_lib/shopManagerRecipients.js";
import type * as _lib_staffAccess from "../_lib/staffAccess.js";
import type * as _lib_submissionPattern from "../_lib/submissionPattern.js";
import type * as _lib_submissionPatternConstants from "../_lib/submissionPatternConstants.js";
import type * as _lib_time from "../_lib/time.js";
import type * as _lib_turnstile from "../_lib/turnstile.js";
import type * as _lib_uuid from "../_lib/uuid.js";
import type * as _lib_validation from "../_lib/validation.js";
import type * as _test_scenarioBuilders from "../_test/scenarioBuilders.js";
import type * as _test_scenarioFixtures from "../_test/scenarioFixtures.js";
import type * as _test_seed from "../_test/seed.js";
import type * as accountDeletion_actions from "../accountDeletion/actions.js";
import type * as accountDeletion_config from "../accountDeletion/config.js";
import type * as accountDeletion_constants from "../accountDeletion/constants.js";
import type * as accountDeletion_httpActions from "../accountDeletion/httpActions.js";
import type * as accountDeletion_mutations from "../accountDeletion/mutations.js";
import type * as accountDeletion_provider from "../accountDeletion/provider.js";
import type * as accountDeletion_queries from "../accountDeletion/queries.js";
import type * as accountDeletion_schemas from "../accountDeletion/schemas.js";
import type * as analytics_backfill from "../analytics/backfill.js";
import type * as analytics_dailyAggregation from "../analytics/dailyAggregation.js";
import type * as analytics_metrics from "../analytics/metrics.js";
import type * as analytics_mutations from "../analytics/mutations.js";
import type * as analytics_queries from "../analytics/queries.js";
import type * as analytics_stage from "../analytics/stage.js";
import type * as analyticsDashboard_dto from "../analyticsDashboard/dto.js";
import type * as analyticsDashboard_httpActions from "../analyticsDashboard/httpActions.js";
import type * as analyticsDashboard_queries from "../analyticsDashboard/queries.js";
import type * as analyticsDashboard_refs from "../analyticsDashboard/refs.js";
import type * as analyticsDashboard_schemas from "../analyticsDashboard/schemas.js";
import type * as billing_service from "../billing/service.js";
import type * as constants from "../constants.js";
import type * as contact_actions from "../contact/actions.js";
import type * as contact_httpActions from "../contact/httpActions.js";
import type * as contact_mutations from "../contact/mutations.js";
import type * as contact_schemas from "../contact/schemas.js";
import type * as crons from "../crons.js";
import type * as dashboard_mutations from "../dashboard/mutations.js";
import type * as dashboard_queries from "../dashboard/queries.js";
import type * as deletionCleanup_mutations from "../deletionCleanup/mutations.js";
import type * as deletionCleanup_queries from "../deletionCleanup/queries.js";
import type * as deletionCleanup_service from "../deletionCleanup/service.js";
import type * as deletionCleanup_tombstone from "../deletionCleanup/tombstone.js";
import type * as deletionCleanup_validators from "../deletionCleanup/validators.js";
import type * as featureRequest_mutations from "../featureRequest/mutations.js";
import type * as featureRequest_schemas from "../featureRequest/schemas.js";
import type * as http from "../http.js";
import type * as legal_actions from "../legal/actions.js";
import type * as legal_documents from "../legal/documents.js";
import type * as legal_mutations from "../legal/mutations.js";
import type * as legal_queries from "../legal/queries.js";
import type * as legal_service from "../legal/service.js";
import type * as line_actions from "../line/actions.js";
import type * as line_mutations from "../line/mutations.js";
import type * as line_queries from "../line/queries.js";
import type * as line_schemas from "../line/schemas.js";
import type * as line_service from "../line/service.js";
import type * as line_webhook from "../line/webhook.js";
import type * as migrations_index from "../migrations/index.js";
import type * as migrations_m001_recruitments_add_shift_times from "../migrations/m001_recruitments_add_shift_times.js";
import type * as migrations_m002_shops_add_submission_pattern from "../migrations/m002_shops_add_submission_pattern.js";
import type * as migrations_m003_recruitments_add_submission_pattern from "../migrations/m003_recruitments_add_submission_pattern.js";
import type * as migrations_m004_notification_failure_inbox_backfill from "../migrations/m004_notification_failure_inbox_backfill.js";
import type * as migrations_m005_shop_billing_states_backfill_free from "../migrations/m005_shop_billing_states_backfill_free.js";
import type * as migrations_m006_notification_failure_inbox_collapse_duplicates from "../migrations/m006_notification_failure_inbox_collapse_duplicates.js";
import type * as migrations_m007_shops_strip_legacy_shift_times from "../migrations/m007_shops_strip_legacy_shift_times.js";
import type * as migrations_m008_recruitments_strip_legacy_shift_times from "../migrations/m008_recruitments_strip_legacy_shift_times.js";
import type * as migrations_m009_shops_to_organizations from "../migrations/m009_shops_to_organizations.js";
import type * as migrations_m010_shop_members_to_organization_members from "../migrations/m010_shop_members_to_organization_members.js";
import type * as migrations_m011_staffs_to_organization_people from "../migrations/m011_staffs_to_organization_people.js";
import type * as migrations_m012_organizations_add_complimentary_business from "../migrations/m012_organizations_add_complimentary_business.js";
import type * as migrations_m013_former_managers_remove_manager_access from "../migrations/m013_former_managers_remove_manager_access.js";
import type * as migrations_m014_removed_organization_members_delete_legacy_shop_members from "../migrations/m014_removed_organization_members_delete_legacy_shop_members.js";
import type * as migrations_m015_organization_invitations_link_lifecycle from "../migrations/m015_organization_invitations_link_lifecycle.js";
import type * as migrations_m016_deleted_shops_enqueue_cleanup_jobs from "../migrations/m016_deleted_shops_enqueue_cleanup_jobs.js";
import type * as migrations_m017_deleted_organizations_enqueue_cleanup_jobs from "../migrations/m017_deleted_organizations_enqueue_cleanup_jobs.js";
import type * as migrations_m018_organization_billing_business_to_pro from "../migrations/m018_organization_billing_business_to_pro.js";
import type * as migrations_m019_notification_outbox_terminal_redaction from "../migrations/m019_notification_outbox_terminal_redaction.js";
import type * as migrations_m020_notification_failure_inbox_redaction from "../migrations/m020_notification_failure_inbox_redaction.js";
import type * as migrations_m021_organization_billing_complimentary_pro_to_business from "../migrations/m021_organization_billing_complimentary_pro_to_business.js";
import type * as migrations_organizationMigrationHelpers from "../migrations/organizationMigrationHelpers.js";
import type * as notification_actions from "../notification/actions.js";
import type * as notification_confirmationSnapshots from "../notification/confirmationSnapshots.js";
import type * as notification_failureRecording from "../notification/failureRecording.js";
import type * as notification_fanout from "../notification/fanout.js";
import type * as notification_mutations from "../notification/mutations.js";
import type * as notification_queries from "../notification/queries.js";
import type * as notification_reminderActions from "../notification/reminderActions.js";
import type * as notification_reminderQueries from "../notification/reminderQueries.js";
import type * as notification_templates from "../notification/templates.js";
import type * as notificationOutbox_actions from "../notificationOutbox/actions.js";
import type * as notificationOutbox_enqueue from "../notificationOutbox/enqueue.js";
import type * as notificationOutbox_failureEligibility from "../notificationOutbox/failureEligibility.js";
import type * as notificationOutbox_failureIdentity from "../notificationOutbox/failureIdentity.js";
import type * as notificationOutbox_failureReminderActions from "../notificationOutbox/failureReminderActions.js";
import type * as notificationOutbox_failureReminderQueries from "../notificationOutbox/failureReminderQueries.js";
import type * as notificationOutbox_failureResend from "../notificationOutbox/failureResend.js";
import type * as notificationOutbox_failureSuppress from "../notificationOutbox/failureSuppress.js";
import type * as notificationOutbox_history from "../notificationOutbox/history.js";
import type * as notificationOutbox_maintenance from "../notificationOutbox/maintenance.js";
import type * as notificationOutbox_mutations from "../notificationOutbox/mutations.js";
import type * as notificationOutbox_origin from "../notificationOutbox/origin.js";
import type * as notificationOutbox_queries from "../notificationOutbox/queries.js";
import type * as notificationOutbox_redaction from "../notificationOutbox/redaction.js";
import type * as notificationOutbox_resendProviderEvents from "../notificationOutbox/resendProviderEvents.js";
import type * as notificationOutbox_resendWebhook from "../notificationOutbox/resendWebhook.js";
import type * as notificationOutbox_safeError from "../notificationOutbox/safeError.js";
import type * as notificationOutbox_schemas from "../notificationOutbox/schemas.js";
import type * as notificationOutbox_types from "../notificationOutbox/types.js";
import type * as organization_access from "../organization/access.js";
import type * as organization_audit from "../organization/audit.js";
import type * as organization_deletion from "../organization/deletion.js";
import type * as organization_managerInvitationState from "../organization/managerInvitationState.js";
import type * as organization_migrations from "../organization/migrations.js";
import type * as organization_mutations from "../organization/mutations.js";
import type * as organization_personCapabilities from "../organization/personCapabilities.js";
import type * as organization_personProfile from "../organization/personProfile.js";
import type * as organization_personRemoval from "../organization/personRemoval.js";
import type * as organization_queries from "../organization/queries.js";
import type * as organization_schemas from "../organization/schemas.js";
import type * as organization_service from "../organization/service.js";
import type * as organization_userDetailQueries from "../organization/userDetailQueries.js";
import type * as organization_validators from "../organization/validators.js";
import type * as organizationBilling_actions from "../organizationBilling/actions.js";
import type * as organizationBilling_deadline from "../organizationBilling/deadline.js";
import type * as organizationBilling_mutations from "../organizationBilling/mutations.js";
import type * as organizationBilling_notification from "../organizationBilling/notification.js";
import type * as organizationBilling_policy from "../organizationBilling/policy.js";
import type * as organizationBilling_queries from "../organizationBilling/queries.js";
import type * as organizationBilling_service from "../organizationBilling/service.js";
import type * as organizationInvitation_actions from "../organizationInvitation/actions.js";
import type * as organizationInvitation_constants from "../organizationInvitation/constants.js";
import type * as organizationInvitation_lifecycle from "../organizationInvitation/lifecycle.js";
import type * as organizationInvitation_mutations from "../organizationInvitation/mutations.js";
import type * as organizationInvitation_purpose from "../organizationInvitation/purpose.js";
import type * as organizationInvitation_queries from "../organizationInvitation/queries.js";
import type * as organizationInvitation_schemas from "../organizationInvitation/schemas.js";
import type * as organizationInvitation_service from "../organizationInvitation/service.js";
import type * as organizationInvitation_token from "../organizationInvitation/token.js";
import type * as organizationStripe_actions from "../organizationStripe/actions.js";
import type * as organizationStripe_config from "../organizationStripe/config.js";
import type * as organizationStripe_maintenance from "../organizationStripe/maintenance.js";
import type * as organizationStripe_mutations from "../organizationStripe/mutations.js";
import type * as organizationStripe_queries from "../organizationStripe/queries.js";
import type * as organizationStripe_validators from "../organizationStripe/validators.js";
import type * as organizationStripe_webhook from "../organizationStripe/webhook.js";
import type * as position_service from "../position/service.js";
import type * as recruitment_mutations from "../recruitment/mutations.js";
import type * as recruitment_schemas from "../recruitment/schemas.js";
import type * as recruitment_service from "../recruitment/service.js";
import type * as setup_mutations from "../setup/mutations.js";
import type * as setup_schemas from "../setup/schemas.js";
import type * as shiftBoard_mutations from "../shiftBoard/mutations.js";
import type * as shiftBoard_queries from "../shiftBoard/queries.js";
import type * as shiftBoard_validation from "../shiftBoard/validation.js";
import type * as shiftConfirmationReminder_actions from "../shiftConfirmationReminder/actions.js";
import type * as shiftConfirmationReminder_queries from "../shiftConfirmationReminder/queries.js";
import type * as shiftSubmission_mutations from "../shiftSubmission/mutations.js";
import type * as shiftSubmission_queries from "../shiftSubmission/queries.js";
import type * as shiftSubmission_schemas from "../shiftSubmission/schemas.js";
import type * as shiftView_queries from "../shiftView/queries.js";
import type * as shop_mutations from "../shop/mutations.js";
import type * as shop_schemas from "../shop/schemas.js";
import type * as shopActivationReminder_actions from "../shopActivationReminder/actions.js";
import type * as shopActivationReminder_queries from "../shopActivationReminder/queries.js";
import type * as shopActivationReminder_refs from "../shopActivationReminder/refs.js";
import type * as staff_mutations from "../staff/mutations.js";
import type * as staff_queries from "../staff/queries.js";
import type * as staff_schemas from "../staff/schemas.js";
import type * as staff_service from "../staff/service.js";
import type * as staffAuth_mutations from "../staffAuth/mutations.js";
import type * as staffAuth_queries from "../staffAuth/queries.js";
import type * as staffAuth_schemas from "../staffAuth/schemas.js";
import type * as staffRegistration_actions from "../staffRegistration/actions.js";
import type * as staffRegistration_httpActions from "../staffRegistration/httpActions.js";
import type * as staffRegistration_mutations from "../staffRegistration/mutations.js";
import type * as staffRegistration_notificationQueries from "../staffRegistration/notificationQueries.js";
import type * as staffRegistration_queries from "../staffRegistration/queries.js";
import type * as staffRegistration_schemas from "../staffRegistration/schemas.js";
import type * as testing from "../testing.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_lib/activeShop": typeof _lib_activeShop;
  "_lib/auditCorrelation": typeof _lib_auditCorrelation;
  "_lib/config": typeof _lib_config;
  "_lib/dashboardUrl": typeof _lib_dashboardUrl;
  "_lib/dateFormat": typeof _lib_dateFormat;
  "_lib/emailFormat": typeof _lib_emailFormat;
  "_lib/functions": typeof _lib_functions;
  "_lib/httpBody": typeof _lib_httpBody;
  "_lib/lineClient": typeof _lib_lineClient;
  "_lib/lineCta": typeof _lib_lineCta;
  "_lib/lineSignature": typeof _lib_lineSignature;
  "_lib/lineUrl": typeof _lib_lineUrl;
  "_lib/notification": typeof _lib_notification;
  "_lib/notificationDelivery": typeof _lib_notificationDelivery;
  "_lib/notificationDeliveryQueries": typeof _lib_notificationDeliveryQueries;
  "_lib/previousWeeklyPattern": typeof _lib_previousWeeklyPattern;
  "_lib/rateLimits": typeof _lib_rateLimits;
  "_lib/resend": typeof _lib_resend;
  "_lib/resendWebhookSignature": typeof _lib_resendWebhookSignature;
  "_lib/shopManagerRecipients": typeof _lib_shopManagerRecipients;
  "_lib/staffAccess": typeof _lib_staffAccess;
  "_lib/submissionPattern": typeof _lib_submissionPattern;
  "_lib/submissionPatternConstants": typeof _lib_submissionPatternConstants;
  "_lib/time": typeof _lib_time;
  "_lib/turnstile": typeof _lib_turnstile;
  "_lib/uuid": typeof _lib_uuid;
  "_lib/validation": typeof _lib_validation;
  "_test/scenarioBuilders": typeof _test_scenarioBuilders;
  "_test/scenarioFixtures": typeof _test_scenarioFixtures;
  "_test/seed": typeof _test_seed;
  "accountDeletion/actions": typeof accountDeletion_actions;
  "accountDeletion/config": typeof accountDeletion_config;
  "accountDeletion/constants": typeof accountDeletion_constants;
  "accountDeletion/httpActions": typeof accountDeletion_httpActions;
  "accountDeletion/mutations": typeof accountDeletion_mutations;
  "accountDeletion/provider": typeof accountDeletion_provider;
  "accountDeletion/queries": typeof accountDeletion_queries;
  "accountDeletion/schemas": typeof accountDeletion_schemas;
  "analytics/backfill": typeof analytics_backfill;
  "analytics/dailyAggregation": typeof analytics_dailyAggregation;
  "analytics/metrics": typeof analytics_metrics;
  "analytics/mutations": typeof analytics_mutations;
  "analytics/queries": typeof analytics_queries;
  "analytics/stage": typeof analytics_stage;
  "analyticsDashboard/dto": typeof analyticsDashboard_dto;
  "analyticsDashboard/httpActions": typeof analyticsDashboard_httpActions;
  "analyticsDashboard/queries": typeof analyticsDashboard_queries;
  "analyticsDashboard/refs": typeof analyticsDashboard_refs;
  "analyticsDashboard/schemas": typeof analyticsDashboard_schemas;
  "billing/service": typeof billing_service;
  constants: typeof constants;
  "contact/actions": typeof contact_actions;
  "contact/httpActions": typeof contact_httpActions;
  "contact/mutations": typeof contact_mutations;
  "contact/schemas": typeof contact_schemas;
  crons: typeof crons;
  "dashboard/mutations": typeof dashboard_mutations;
  "dashboard/queries": typeof dashboard_queries;
  "deletionCleanup/mutations": typeof deletionCleanup_mutations;
  "deletionCleanup/queries": typeof deletionCleanup_queries;
  "deletionCleanup/service": typeof deletionCleanup_service;
  "deletionCleanup/tombstone": typeof deletionCleanup_tombstone;
  "deletionCleanup/validators": typeof deletionCleanup_validators;
  "featureRequest/mutations": typeof featureRequest_mutations;
  "featureRequest/schemas": typeof featureRequest_schemas;
  http: typeof http;
  "legal/actions": typeof legal_actions;
  "legal/documents": typeof legal_documents;
  "legal/mutations": typeof legal_mutations;
  "legal/queries": typeof legal_queries;
  "legal/service": typeof legal_service;
  "line/actions": typeof line_actions;
  "line/mutations": typeof line_mutations;
  "line/queries": typeof line_queries;
  "line/schemas": typeof line_schemas;
  "line/service": typeof line_service;
  "line/webhook": typeof line_webhook;
  "migrations/index": typeof migrations_index;
  "migrations/m001_recruitments_add_shift_times": typeof migrations_m001_recruitments_add_shift_times;
  "migrations/m002_shops_add_submission_pattern": typeof migrations_m002_shops_add_submission_pattern;
  "migrations/m003_recruitments_add_submission_pattern": typeof migrations_m003_recruitments_add_submission_pattern;
  "migrations/m004_notification_failure_inbox_backfill": typeof migrations_m004_notification_failure_inbox_backfill;
  "migrations/m005_shop_billing_states_backfill_free": typeof migrations_m005_shop_billing_states_backfill_free;
  "migrations/m006_notification_failure_inbox_collapse_duplicates": typeof migrations_m006_notification_failure_inbox_collapse_duplicates;
  "migrations/m007_shops_strip_legacy_shift_times": typeof migrations_m007_shops_strip_legacy_shift_times;
  "migrations/m008_recruitments_strip_legacy_shift_times": typeof migrations_m008_recruitments_strip_legacy_shift_times;
  "migrations/m009_shops_to_organizations": typeof migrations_m009_shops_to_organizations;
  "migrations/m010_shop_members_to_organization_members": typeof migrations_m010_shop_members_to_organization_members;
  "migrations/m011_staffs_to_organization_people": typeof migrations_m011_staffs_to_organization_people;
  "migrations/m012_organizations_add_complimentary_business": typeof migrations_m012_organizations_add_complimentary_business;
  "migrations/m013_former_managers_remove_manager_access": typeof migrations_m013_former_managers_remove_manager_access;
  "migrations/m014_removed_organization_members_delete_legacy_shop_members": typeof migrations_m014_removed_organization_members_delete_legacy_shop_members;
  "migrations/m015_organization_invitations_link_lifecycle": typeof migrations_m015_organization_invitations_link_lifecycle;
  "migrations/m016_deleted_shops_enqueue_cleanup_jobs": typeof migrations_m016_deleted_shops_enqueue_cleanup_jobs;
  "migrations/m017_deleted_organizations_enqueue_cleanup_jobs": typeof migrations_m017_deleted_organizations_enqueue_cleanup_jobs;
  "migrations/m018_organization_billing_business_to_pro": typeof migrations_m018_organization_billing_business_to_pro;
  "migrations/m019_notification_outbox_terminal_redaction": typeof migrations_m019_notification_outbox_terminal_redaction;
  "migrations/m020_notification_failure_inbox_redaction": typeof migrations_m020_notification_failure_inbox_redaction;
  "migrations/m021_organization_billing_complimentary_pro_to_business": typeof migrations_m021_organization_billing_complimentary_pro_to_business;
  "migrations/organizationMigrationHelpers": typeof migrations_organizationMigrationHelpers;
  "notification/actions": typeof notification_actions;
  "notification/confirmationSnapshots": typeof notification_confirmationSnapshots;
  "notification/failureRecording": typeof notification_failureRecording;
  "notification/fanout": typeof notification_fanout;
  "notification/mutations": typeof notification_mutations;
  "notification/queries": typeof notification_queries;
  "notification/reminderActions": typeof notification_reminderActions;
  "notification/reminderQueries": typeof notification_reminderQueries;
  "notification/templates": typeof notification_templates;
  "notificationOutbox/actions": typeof notificationOutbox_actions;
  "notificationOutbox/enqueue": typeof notificationOutbox_enqueue;
  "notificationOutbox/failureEligibility": typeof notificationOutbox_failureEligibility;
  "notificationOutbox/failureIdentity": typeof notificationOutbox_failureIdentity;
  "notificationOutbox/failureReminderActions": typeof notificationOutbox_failureReminderActions;
  "notificationOutbox/failureReminderQueries": typeof notificationOutbox_failureReminderQueries;
  "notificationOutbox/failureResend": typeof notificationOutbox_failureResend;
  "notificationOutbox/failureSuppress": typeof notificationOutbox_failureSuppress;
  "notificationOutbox/history": typeof notificationOutbox_history;
  "notificationOutbox/maintenance": typeof notificationOutbox_maintenance;
  "notificationOutbox/mutations": typeof notificationOutbox_mutations;
  "notificationOutbox/origin": typeof notificationOutbox_origin;
  "notificationOutbox/queries": typeof notificationOutbox_queries;
  "notificationOutbox/redaction": typeof notificationOutbox_redaction;
  "notificationOutbox/resendProviderEvents": typeof notificationOutbox_resendProviderEvents;
  "notificationOutbox/resendWebhook": typeof notificationOutbox_resendWebhook;
  "notificationOutbox/safeError": typeof notificationOutbox_safeError;
  "notificationOutbox/schemas": typeof notificationOutbox_schemas;
  "notificationOutbox/types": typeof notificationOutbox_types;
  "organization/access": typeof organization_access;
  "organization/audit": typeof organization_audit;
  "organization/deletion": typeof organization_deletion;
  "organization/managerInvitationState": typeof organization_managerInvitationState;
  "organization/migrations": typeof organization_migrations;
  "organization/mutations": typeof organization_mutations;
  "organization/personCapabilities": typeof organization_personCapabilities;
  "organization/personProfile": typeof organization_personProfile;
  "organization/personRemoval": typeof organization_personRemoval;
  "organization/queries": typeof organization_queries;
  "organization/schemas": typeof organization_schemas;
  "organization/service": typeof organization_service;
  "organization/userDetailQueries": typeof organization_userDetailQueries;
  "organization/validators": typeof organization_validators;
  "organizationBilling/actions": typeof organizationBilling_actions;
  "organizationBilling/deadline": typeof organizationBilling_deadline;
  "organizationBilling/mutations": typeof organizationBilling_mutations;
  "organizationBilling/notification": typeof organizationBilling_notification;
  "organizationBilling/policy": typeof organizationBilling_policy;
  "organizationBilling/queries": typeof organizationBilling_queries;
  "organizationBilling/service": typeof organizationBilling_service;
  "organizationInvitation/actions": typeof organizationInvitation_actions;
  "organizationInvitation/constants": typeof organizationInvitation_constants;
  "organizationInvitation/lifecycle": typeof organizationInvitation_lifecycle;
  "organizationInvitation/mutations": typeof organizationInvitation_mutations;
  "organizationInvitation/purpose": typeof organizationInvitation_purpose;
  "organizationInvitation/queries": typeof organizationInvitation_queries;
  "organizationInvitation/schemas": typeof organizationInvitation_schemas;
  "organizationInvitation/service": typeof organizationInvitation_service;
  "organizationInvitation/token": typeof organizationInvitation_token;
  "organizationStripe/actions": typeof organizationStripe_actions;
  "organizationStripe/config": typeof organizationStripe_config;
  "organizationStripe/maintenance": typeof organizationStripe_maintenance;
  "organizationStripe/mutations": typeof organizationStripe_mutations;
  "organizationStripe/queries": typeof organizationStripe_queries;
  "organizationStripe/validators": typeof organizationStripe_validators;
  "organizationStripe/webhook": typeof organizationStripe_webhook;
  "position/service": typeof position_service;
  "recruitment/mutations": typeof recruitment_mutations;
  "recruitment/schemas": typeof recruitment_schemas;
  "recruitment/service": typeof recruitment_service;
  "setup/mutations": typeof setup_mutations;
  "setup/schemas": typeof setup_schemas;
  "shiftBoard/mutations": typeof shiftBoard_mutations;
  "shiftBoard/queries": typeof shiftBoard_queries;
  "shiftBoard/validation": typeof shiftBoard_validation;
  "shiftConfirmationReminder/actions": typeof shiftConfirmationReminder_actions;
  "shiftConfirmationReminder/queries": typeof shiftConfirmationReminder_queries;
  "shiftSubmission/mutations": typeof shiftSubmission_mutations;
  "shiftSubmission/queries": typeof shiftSubmission_queries;
  "shiftSubmission/schemas": typeof shiftSubmission_schemas;
  "shiftView/queries": typeof shiftView_queries;
  "shop/mutations": typeof shop_mutations;
  "shop/schemas": typeof shop_schemas;
  "shopActivationReminder/actions": typeof shopActivationReminder_actions;
  "shopActivationReminder/queries": typeof shopActivationReminder_queries;
  "shopActivationReminder/refs": typeof shopActivationReminder_refs;
  "staff/mutations": typeof staff_mutations;
  "staff/queries": typeof staff_queries;
  "staff/schemas": typeof staff_schemas;
  "staff/service": typeof staff_service;
  "staffAuth/mutations": typeof staffAuth_mutations;
  "staffAuth/queries": typeof staffAuth_queries;
  "staffAuth/schemas": typeof staffAuth_schemas;
  "staffRegistration/actions": typeof staffRegistration_actions;
  "staffRegistration/httpActions": typeof staffRegistration_httpActions;
  "staffRegistration/mutations": typeof staffRegistration_mutations;
  "staffRegistration/notificationQueries": typeof staffRegistration_notificationQueries;
  "staffRegistration/queries": typeof staffRegistration_queries;
  "staffRegistration/schemas": typeof staffRegistration_schemas;
  testing: typeof testing;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
