import type { Recruitment, Staff } from "./types";

// Storybook用モックデータ。_id は Convex ID の型だが、stories では文字列で代用する
export const mockRecruitments = [
  {
    _id: "rec-1",
    createdAt: 1_781_420_000_000,
    periodStart: "2026-07-02",
    periodEnd: "2026-07-24",
    deadline: "2026-06-25",
    shopClosedDates: [],
    status: "open",
    confirmedAt: null,
    responseCount: 1,
    totalStaffCount: 10,
  },
  {
    _id: "rec-2",
    createdAt: 1_781_333_600_000,
    periodStart: "2026-07-01",
    periodEnd: "2026-07-31",
    deadline: "2026-06-30",
    shopClosedDates: [],
    status: "open",
    confirmedAt: null,
    responseCount: 0,
    totalStaffCount: 10,
  },
  {
    _id: "rec-3",
    createdAt: 1_781_247_200_000,
    periodStart: "2026-06-19",
    periodEnd: "2026-06-26",
    deadline: "2026-06-10",
    shopClosedDates: [],
    status: "open",
    confirmedAt: null,
    responseCount: 0,
    totalStaffCount: 10,
  },
  {
    _id: "rec-current",
    createdAt: 1_781_160_800_000,
    periodStart: "2026-06-09",
    periodEnd: "2026-06-30",
    deadline: "2026-06-07",
    shopClosedDates: [],
    status: "confirmed",
    confirmedAt: 1_781_333_600_000,
    responseCount: 10,
    totalStaffCount: 10,
  },
  {
    _id: "rec-ended",
    createdAt: 1_779_778_400_000,
    periodStart: "2026-05-01",
    periodEnd: "2026-05-15",
    deadline: "2026-04-25",
    shopClosedDates: [],
    status: "confirmed",
    confirmedAt: 1_778_914_400_000,
    responseCount: 10,
    totalStaffCount: 10,
  },
] as unknown as Recruitment[];

export const mockCurrentRecruitments = [mockRecruitments[3]];

export const mockStaffs = [
  {
    _id: "s1",
    name: "田中太郎",
    email: "tanaka@example.com",
    isManager: true,
    isLineLinked: true,
    isLineFollowing: true,
  },
  {
    _id: "s2",
    name: "佐藤花子",
    email: "sato@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
  {
    _id: "s3",
    name: "鈴木一郎",
    email: "suzuki@example.com",
    isManager: false,
    isLineLinked: true,
    isLineFollowing: false,
  },
] as unknown as Staff[];

export const mockStaffsWithExcluded = [
  {
    _id: "s1",
    name: "店舗共通アドレス",
    email: "shop@example.com",
    isManager: true,
    isLineLinked: false,
    isLineFollowing: false,
    excludedFromShift: true,
  },
  {
    _id: "s2",
    name: "佐藤花子",
    email: "sato@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
    excludedFromShift: false,
  },
  {
    _id: "s3",
    name: "鈴木一郎",
    email: "suzuki@example.com",
    isManager: false,
    isLineLinked: true,
    isLineFollowing: false,
    excludedFromShift: true,
  },
] as unknown as Staff[];

export const mockStaffsMany = [
  {
    _id: "s1",
    name: "田中太郎",
    email: "tanaka@example.com",
    isManager: true,
    isLineLinked: true,
    isLineFollowing: true,
  },
  {
    _id: "s2",
    name: "佐藤花子",
    email: "sato@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
  {
    _id: "s3",
    name: "鈴木一郎",
    email: "suzuki@example.com",
    isManager: false,
    isLineLinked: true,
    isLineFollowing: true,
  },
  {
    _id: "s4",
    name: "山田美咲",
    email: "yamada@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
  {
    _id: "s5",
    name: "高橋健太",
    email: "takahashi@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
  {
    _id: "s6",
    name: "伊藤麻衣",
    email: "ito@example.com",
    isManager: false,
    isLineLinked: true,
    isLineFollowing: false,
  },
  {
    _id: "s7",
    name: "渡辺翔太",
    email: "watanabe@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
  {
    _id: "s8",
    name: "中村由美",
    email: "nakamura@example.com",
    isManager: false,
    isLineLinked: true,
    isLineFollowing: true,
  },
  {
    _id: "s9",
    name: "小林大輔",
    email: "kobayashi@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
  {
    _id: "s10",
    name: "加藤彩",
    email: "kato@example.com",
    isManager: false,
    isLineLinked: false,
    isLineFollowing: false,
  },
] as unknown as Staff[];
