export type {
  AnalyticsAvailability,
  AnalyticsCadenceDto,
  AnalyticsCompleteness,
  AnalyticsCountSummaryDto,
  AnalyticsCycleRowDto,
  AnalyticsDashboardResponse,
  AnalyticsDirection,
  AnalyticsGranularity,
  AnalyticsHealthPointDto,
  AnalyticsHealthSignalCountsDto,
  AnalyticsHealthSignalDto,
  AnalyticsHealthSignalKey,
  AnalyticsMilestoneCountsDto,
  AnalyticsMilestoneDatesDto,
  AnalyticsMilestoneKey,
  AnalyticsMilestonePointDto,
  AnalyticsMilestoneRatesDto,
  AnalyticsNullableRateDto,
  AnalyticsOrganizationKpiDto,
  AnalyticsOrganizationRowDto,
  AnalyticsPageInfoDto,
  AnalyticsPlanKey,
  AnalyticsRateDto,
  AnalyticsRateRangeDto,
  AnalyticsResponseMetadata,
  AnalyticsSegmentDimension,
  AnalyticsSegmentRowDto,
  AnalyticsServiceKpiSnapshotDto,
  AnalyticsShopKpiDto,
  AnalyticsShopListRowDto,
  AnalyticsShopRowDto,
  AnalyticsShopUsageLikelihood,
  AnalyticsShopUsageReason,
  AnalyticsTrendMetric,
  AnalyticsTrendPointDto,
  AnalyticsTrendValueDto,
  CanonicalAnalyticsPlanKey,
  CycleDetailResponse,
  FeatureRequestRowDto,
  FeatureRequestsResponse,
  HealthResponse,
  MilestonesResponse,
  OrganizationDetailResponse,
  OrganizationsResponse,
  OverviewResponse,
  SegmentsResponse,
  ShopCyclesResponse,
  ShopDetailResponse,
  ShopsResponse,
  TrendsResponse,
} from "@convex/analyticsDashboard/dto";

export type {
  AnalyticsCadenceFilter,
  AnalyticsCycleSort,
  AnalyticsLineUsageFilter,
  AnalyticsOrganizationSort,
  AnalyticsSegmentSort,
  AnalyticsShopSizeFilter,
  AnalyticsShopSort,
  AnalyticsShopUsageFilter,
} from "@convex/analyticsDashboard/schemas";

export type AnalyticsApiEnvelope<T> = {
  env: {
    label: string;
  };
  data: T;
};
