import { existsSync, readdirSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { articleSlugAliases, resolveArticleSlug } from "../src/components/features/ArticleSite/articleAliases";

export const STATIC_CLIENT_OUTPUT_DIR = "dist/client";
export const STATIC_404_BUILD_PATH = "/__static-404";

export const FIXED_PUBLIC_ROUTES = [
  "/",
  "/account-deletion-accepted",
  "/articles",
  "/cache-reset",
  "/contact",
  "/demo/flow",
  "/demo/shiftboard",
  "/faq",
  "/features",
  "/howto",
  "/privacy",
  "/privacy/manager",
  "/privacy/staff",
  "/terms",
  "/terms/manager",
  "/terms/staff",
] as const;

export const NOINDEX_PUBLIC_ROUTES = new Set<string>([
  "/account-deletion-accepted",
  "/cache-reset",
  "/privacy",
  "/privacy/manager",
  "/privacy/staff",
  "/terms",
  "/terms/manager",
  "/terms/staff",
]);

/** Queryを含めず、指定されたpathだけをCSR shellへ渡す。 */
export const CSR_SHELL_STATIC_ROUTES = [
  "/dashboard",
  "/forgot-password",
  "/legal/staff/consent",
  "/line/callback",
  "/login",
  "/manager-invite",
  "/settings",
  "/shifts/reissue",
  "/shifts/submit",
  "/shifts/submit/completed",
  "/shifts/view",
  "/signup",
  "/sso-callback",
  "/staff/register",
] as const;

/** Cloudflare Pagesのnamed placeholder。長いpathを先に評価する。 */
export const CSR_SHELL_DYNAMIC_ROUTES = [
  "/users/:personId/shops/:targetShopId",
  "/shiftboard/:recruitmentId",
  "/shops/:shopId",
  "/users/:personId",
] as const;

const ARTICLE_CONTENT_DIR = join("src", "components", "features", "ArticleSite", "content");
const LOOPBACK_URL_PATTERN = /https?:\/\/(?:localhost|127(?:\.\d{1,3}){3}|\[::1\])(?::\d+)?(?:\/[^\s"'<>]*)?/i;

export function assertNoLoopbackUrls(route: string, html: string): void {
  const match = html.match(LOOPBACK_URL_PATTERN);
  if (!match) return;

  throw new Error(`[static-build] ${route} contains a loopback URL (${match[0]})`);
}

function listPublishedContentSlugs(repoRoot: string, kind: "articles" | "categories"): string[] {
  const directory = resolve(repoRoot, ARTICLE_CONTENT_DIR, kind);
  return readdirSync(directory, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isDirectory() && !entry.name.startsWith("_") && existsSync(join(directory, entry.name, "index.mdx")),
    )
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));
}

/** SSG対象は公開routeのallowlistだけから構築し、認証・Capability routeを自動探索しない。 */
export function collectPublicRoutes(repoRoot = process.cwd()): string[] {
  const articleSlugs = listPublishedContentSlugs(repoRoot, "articles");
  for (const [alias, target] of Object.entries(articleSlugAliases)) {
    if (!articleSlugs.includes(target)) {
      throw new Error(`Article alias "${alias}" points to unpublished slug "${target}"`);
    }
    if (articleSlugs.includes(alias)) {
      throw new Error(`Article alias "${alias}" conflicts with a published content directory`);
    }
  }

  const articleRoutes = [...articleSlugs, ...Object.keys(articleSlugAliases)].map((slug) => `/articles/${slug}`);
  const categoryRoutes = listPublishedContentSlugs(repoRoot, "categories").map(
    (slug) => `/articles/categories/${slug}`,
  );

  return Array.from(new Set([...FIXED_PUBLIC_ROUTES, ...articleRoutes, ...categoryRoutes])).sort((left, right) =>
    left.localeCompare(right),
  );
}

/** 互換URLを含め、検索エンジンへ示すno-slash canonical pathを返す。 */
export function getCanonicalRoute(route: string): string {
  const match = route.match(/^\/articles\/([^/]+)$/);
  if (!match?.[1]) return route;
  return `/articles/${resolveArticleSlug(match[1])}`;
}

export function getIndexableCanonicalRoutes(publicRoutes: readonly string[]): string[] {
  return Array.from(
    new Set(publicRoutes.filter((route) => !NOINDEX_PUBLIC_ROUTES.has(route)).map(getCanonicalRoute)),
  ).sort((left, right) => left.localeCompare(right));
}

export function routeToHtmlPath(route: string): string {
  if (route === "/") return "index.html";
  return `${route.slice(1)}.html`;
}

function withOptionalTrailingSlash(route: string): string[] {
  return [route, `${route}/`];
}

export function createCloudflareRedirects(publicRoutes: readonly string[]): string {
  const publicAliases = publicRoutes
    .filter((route) => route !== "/")
    .sort((left, right) => right.split("/").length - left.split("/").length || left.localeCompare(right))
    .map((route) => `${route}/ ${route} 200`);

  const staticShellRules = CSR_SHELL_STATIC_ROUTES.flatMap(withOptionalTrailingSlash).map(
    (route) => `${route} /_shell.html 200`,
  );
  const dynamicShellRules = CSR_SHELL_DYNAMIC_ROUTES.flatMap(withOptionalTrailingSlash).map(
    (route) => `${route} /_shell.html 200`,
  );

  return [
    "# Generated by scripts/prepareStaticDeployment.ts. Do not edit the build artifact.",
    "# Existing public URLs with a trailing slash terminate legacy cached 308 redirects with a 200 proxy.",
    ...publicAliases,
    "",
    "# Authentication and capability URLs are rendered only in the browser from the neutral SPA shell.",
    ...staticShellRules,
    ...dynamicShellRules,
    "",
  ].join("\n");
}

const SHELL_HEADERS = [
  "  Cache-Control: no-store",
  "  X-Robots-Tag: noindex, nofollow",
  "  Referrer-Policy: no-referrer",
] as const;

const CACHE_RESET_HEADERS = [
  '  Clear-Site-Data: "cache"',
  "  Cache-Control: no-store",
  "  X-Robots-Tag: noindex, nofollow",
  "  Referrer-Policy: no-referrer",
] as const;

export function createCloudflareHeaders(publicRoutes: readonly string[]): string {
  const blocks: string[][] = [
    ["/cache-reset", ...CACHE_RESET_HEADERS],
    ["/cache-reset/", ...CACHE_RESET_HEADERS, '  Link: <https://shiftori.app/cache-reset>; rel="canonical"'],
    ["/_shell.html", ...SHELL_HEADERS],
    ["/_shell", ...SHELL_HEADERS],
    ["/404.html", "  Cache-Control: no-store", "  X-Robots-Tag: noindex, nofollow"],
    ["/404", "  Cache-Control: no-store", "  X-Robots-Tag: noindex, nofollow"],
  ];

  for (const route of publicRoutes.filter((path) => path !== "/" && path !== "/cache-reset")) {
    blocks.push([`${route}/`, `  Link: <https://shiftori.app${getCanonicalRoute(route)}>; rel="canonical"`]);
  }

  for (const route of [...CSR_SHELL_STATIC_ROUTES, ...CSR_SHELL_DYNAMIC_ROUTES].flatMap(withOptionalTrailingSlash)) {
    blocks.push([route, ...SHELL_HEADERS]);
  }

  return [
    "# Generated by scripts/prepareStaticDeployment.ts. Do not edit the build artifact.",
    ...blocks.flatMap((block, index) => (index === blocks.length - 1 ? block : [...block, ""])),
    "",
  ].join("\n");
}

export function assertOutputDirectory(outputDirectory: string, repoRoot = process.cwd()): string {
  const resolvedRoot = resolve(repoRoot);
  const resolvedOutput = resolve(repoRoot, outputDirectory);
  const relativeOutput = relative(resolvedRoot, resolvedOutput);
  if (relativeOutput.startsWith("..") || relativeOutput === "") {
    throw new Error(`Static output must be a directory inside the repository: ${resolvedOutput}`);
  }
  return resolvedOutput;
}
