import { createRouter, RouterProvider } from "@tanstack/react-router";
import { type ReactNode, StrictMode } from "react";
import { flushSync } from "react-dom";
import ReactDOM from "react-dom/client";
import z from "zod";
import { RouteErrorFallback } from "@/src/components/ui/ErrorBoundary";
import { GTM_ID } from "@/src/configs/env";
import { customErrorMap } from "@/src/configs/zod/zop-setup.ts";
import { initGTM } from "@/src/lib/gtm";
import { isPrerendering } from "@/src/lib/seo";
import { ChakraProvider } from "@/src/providers/ChakraProvider";
import reportWebVitals from "./reportWebVitals.ts";
import { routeTree } from "./routeTree.gen.ts";

// GTM(→GA4/Clarity)の読み込みを初期描画後まで遅延し、LCP/TBTと帯域を奪い合わないようにする。
// 遅延中のイベントは gtm helper が dataLayer にバッファし、GTM 読み込み時にまとめて処理される。
const scheduleGtmInit =
  typeof window.requestIdleCallback === "function"
    ? (cb: () => void) => window.requestIdleCallback(cb, { timeout: 5000 })
    : (cb: () => void) => window.setTimeout(cb, 3000);
scheduleGtmInit(() => initGTM(GTM_ID));

// Create a new router instance
const router = createRouter({
  routeTree,
  context: {},
  defaultPreload: "intent",
  scrollRestoration: true,
  defaultStructuralSharing: true,
  defaultPreloadStaleTime: 0,
  defaultErrorComponent: RouteErrorFallback,
});

// Register the router instance for type safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

z.config({ customError: customErrorMap });

function removePrerenderedPortals(): void {
  for (const node of document.body.querySelectorAll('[data-scope="toast"][data-part="group"]')) {
    node.remove();
  }
}

async function mountPrerenderedApp(element: HTMLElement, tree: ReactNode): Promise<void> {
  // The post-build prerender output is an SEO/static shell generated by a SPA,
  // not a dehydrated React SSR snapshot. Load the current lazy route first, then
  // replace the baked DOM with the live app to avoid React hydration mismatches.
  await router.load({ sync: true });
  removePrerenderedPortals();
  // replaceChildren と React の初回コミットを flushSync で同一タスク内に収め、
  // 焼き込みDOM除去→再描画の間にブラウザが空白フレームを描く「ちらつき」を防ぐ。
  const root = ReactDOM.createRoot(element);
  element.replaceChildren();
  flushSync(() => {
    root.render(tree);
  });
  // SPAフォールバック時のスプラッシュ（index.html 参照）を、Reactの初回コミット後に解除する
  requestAnimationFrame(() => {
    document.documentElement.removeAttribute("data-spa-fallback");
    document.documentElement.removeAttribute("data-prerender-path");
  });
}

// Render the app
const rootElement = document.getElementById("app");
if (rootElement) {
  // Clerk / Convex は認証が必要なレイアウト側（AuthProviders）でラップする。
  // ここに置くとLPなどの公開ページのバンドル・起動コストに乗ってしまう。
  const tree = (
    <StrictMode>
      <ChakraProvider>
        <RouterProvider router={router} />
      </ChakraProvider>
    </StrictMode>
  );
  if (!isPrerendering() && rootElement.innerHTML.trim()) {
    void mountPrerenderedApp(rootElement, tree);
  } else {
    // 初回 prerender 実行時、または通常 SPA ルート(#app が空シェル) はそのまま mount。
    ReactDOM.createRoot(rootElement).render(tree);
  }
}

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
