/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnregisteredRouteImport } from './routes/_unregistered'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnregisteredWelcomeRouteImport } from './routes/_unregistered/welcome'
import { Route as AuthShiftsRouteImport } from './routes/_auth/shifts'
import { Route as AuthMypageRouteImport } from './routes/_auth/mypage'
import { Route as AuthShopsIndexRouteImport } from './routes/_auth/shops/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthShopsNewIndexRouteImport } from './routes/_auth/shops/new/index'
import { Route as AuthShopsShopIdIndexRouteImport } from './routes/_auth/shops/$shopId/index'
import { Route as AuthSettingsShiftTemplateIndexRouteImport } from './routes/_auth/settings/shift-template/index'
import { Route as AuthSettingsShiftTemplateEditRouteImport } from './routes/_auth/settings/shift-template/edit'
import { Route as AuthSettingsShiftTemplateAddRouteImport } from './routes/_auth/settings/shift-template/add'
import { Route as AuthShopsShopIdEditIndexRouteImport } from './routes/_auth/shops/$shopId/edit/index'
import { Route as AuthShopsShopIdStaffsStaffIdIndexRouteImport } from './routes/_auth/shops/$shopId/staffs/$staffId/index'
import { Route as AuthShopsShopIdStaffsStaffIdEditRouteImport } from './routes/_auth/shops/$shopId/staffs/$staffId/edit'

const UnregisteredRoute = UnregisteredRouteImport.update({
  id: '/_unregistered',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const UnregisteredWelcomeRoute = UnregisteredWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => UnregisteredRoute,
} as any)
const AuthShiftsRoute = AuthShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMypageRoute = AuthMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => AuthRoute,
} as any)
const AuthShopsIndexRoute = AuthShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthShopsNewIndexRoute = AuthShopsNewIndexRouteImport.update({
  id: '/shops/new/',
  path: '/shops/new/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthShopsShopIdIndexRoute = AuthShopsShopIdIndexRouteImport.update({
  id: '/shops/$shopId/',
  path: '/shops/$shopId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsShiftTemplateIndexRoute =
  AuthSettingsShiftTemplateIndexRouteImport.update({
    id: '/settings/shift-template/',
    path: '/settings/shift-template/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsShiftTemplateEditRoute =
  AuthSettingsShiftTemplateEditRouteImport.update({
    id: '/settings/shift-template/edit',
    path: '/settings/shift-template/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsShiftTemplateAddRoute =
  AuthSettingsShiftTemplateAddRouteImport.update({
    id: '/settings/shift-template/add',
    path: '/settings/shift-template/add',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthShopsShopIdEditIndexRoute =
  AuthShopsShopIdEditIndexRouteImport.update({
    id: '/shops/$shopId/edit/',
    path: '/shops/$shopId/edit/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthShopsShopIdStaffsStaffIdIndexRoute =
  AuthShopsShopIdStaffsStaffIdIndexRouteImport.update({
    id: '/shops/$shopId/staffs/$staffId/',
    path: '/shops/$shopId/staffs/$staffId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthShopsShopIdStaffsStaffIdEditRoute =
  AuthShopsShopIdStaffsStaffIdEditRouteImport.update({
    id: '/shops/$shopId/staffs/$staffId/edit',
    path: '/shops/$shopId/staffs/$staffId/edit',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/mypage': typeof AuthMypageRoute
  '/shifts': typeof AuthShiftsRoute
  '/welcome': typeof UnregisteredWelcomeRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/shops': typeof AuthShopsIndexRoute
  '/settings/shift-template/add': typeof AuthSettingsShiftTemplateAddRoute
  '/settings/shift-template/edit': typeof AuthSettingsShiftTemplateEditRoute
  '/settings/shift-template': typeof AuthSettingsShiftTemplateIndexRoute
  '/shops/$shopId': typeof AuthShopsShopIdIndexRoute
  '/shops/new': typeof AuthShopsNewIndexRoute
  '/shops/$shopId/edit': typeof AuthShopsShopIdEditIndexRoute
  '/shops/$shopId/staffs/$staffId/edit': typeof AuthShopsShopIdStaffsStaffIdEditRoute
  '/shops/$shopId/staffs/$staffId': typeof AuthShopsShopIdStaffsStaffIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/mypage': typeof AuthMypageRoute
  '/shifts': typeof AuthShiftsRoute
  '/welcome': typeof UnregisteredWelcomeRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/shops': typeof AuthShopsIndexRoute
  '/settings/shift-template/add': typeof AuthSettingsShiftTemplateAddRoute
  '/settings/shift-template/edit': typeof AuthSettingsShiftTemplateEditRoute
  '/settings/shift-template': typeof AuthSettingsShiftTemplateIndexRoute
  '/shops/$shopId': typeof AuthShopsShopIdIndexRoute
  '/shops/new': typeof AuthShopsNewIndexRoute
  '/shops/$shopId/edit': typeof AuthShopsShopIdEditIndexRoute
  '/shops/$shopId/staffs/$staffId/edit': typeof AuthShopsShopIdStaffsStaffIdEditRoute
  '/shops/$shopId/staffs/$staffId': typeof AuthShopsShopIdStaffsStaffIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_unregistered': typeof UnregisteredRouteWithChildren
  '/_auth/mypage': typeof AuthMypageRoute
  '/_auth/shifts': typeof AuthShiftsRoute
  '/_unregistered/welcome': typeof UnregisteredWelcomeRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/shops/': typeof AuthShopsIndexRoute
  '/_auth/settings/shift-template/add': typeof AuthSettingsShiftTemplateAddRoute
  '/_auth/settings/shift-template/edit': typeof AuthSettingsShiftTemplateEditRoute
  '/_auth/settings/shift-template/': typeof AuthSettingsShiftTemplateIndexRoute
  '/_auth/shops/$shopId/': typeof AuthShopsShopIdIndexRoute
  '/_auth/shops/new/': typeof AuthShopsNewIndexRoute
  '/_auth/shops/$shopId/edit/': typeof AuthShopsShopIdEditIndexRoute
  '/_auth/shops/$shopId/staffs/$staffId/edit': typeof AuthShopsShopIdStaffsStaffIdEditRoute
  '/_auth/shops/$shopId/staffs/$staffId/': typeof AuthShopsShopIdStaffsStaffIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/mypage'
    | '/shifts'
    | '/welcome'
    | '/settings'
    | '/shops'
    | '/settings/shift-template/add'
    | '/settings/shift-template/edit'
    | '/settings/shift-template'
    | '/shops/$shopId'
    | '/shops/new'
    | '/shops/$shopId/edit'
    | '/shops/$shopId/staffs/$staffId/edit'
    | '/shops/$shopId/staffs/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/mypage'
    | '/shifts'
    | '/welcome'
    | '/settings'
    | '/shops'
    | '/settings/shift-template/add'
    | '/settings/shift-template/edit'
    | '/settings/shift-template'
    | '/shops/$shopId'
    | '/shops/new'
    | '/shops/$shopId/edit'
    | '/shops/$shopId/staffs/$staffId/edit'
    | '/shops/$shopId/staffs/$staffId'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/_auth'
    | '/_unregistered'
    | '/_auth/mypage'
    | '/_auth/shifts'
    | '/_unregistered/welcome'
    | '/_auth/settings/'
    | '/_auth/shops/'
    | '/_auth/settings/shift-template/add'
    | '/_auth/settings/shift-template/edit'
    | '/_auth/settings/shift-template/'
    | '/_auth/shops/$shopId/'
    | '/_auth/shops/new/'
    | '/_auth/shops/$shopId/edit/'
    | '/_auth/shops/$shopId/staffs/$staffId/edit'
    | '/_auth/shops/$shopId/staffs/$staffId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  AuthRoute: typeof AuthRouteWithChildren
  UnregisteredRoute: typeof UnregisteredRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unregistered': {
      id: '/_unregistered'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnregisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unregistered/welcome': {
      id: '/_unregistered/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof UnregisteredWelcomeRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_auth/shifts': {
      id: '/_auth/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthShiftsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mypage': {
      id: '/_auth/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof AuthMypageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shops/': {
      id: '/_auth/shops/'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof AuthShopsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shops/new/': {
      id: '/_auth/shops/new/'
      path: '/shops/new'
      fullPath: '/shops/new'
      preLoaderRoute: typeof AuthShopsNewIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shops/$shopId/': {
      id: '/_auth/shops/$shopId/'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/shift-template/': {
      id: '/_auth/settings/shift-template/'
      path: '/settings/shift-template'
      fullPath: '/settings/shift-template'
      preLoaderRoute: typeof AuthSettingsShiftTemplateIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/shift-template/edit': {
      id: '/_auth/settings/shift-template/edit'
      path: '/settings/shift-template/edit'
      fullPath: '/settings/shift-template/edit'
      preLoaderRoute: typeof AuthSettingsShiftTemplateEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/shift-template/add': {
      id: '/_auth/settings/shift-template/add'
      path: '/settings/shift-template/add'
      fullPath: '/settings/shift-template/add'
      preLoaderRoute: typeof AuthSettingsShiftTemplateAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shops/$shopId/edit/': {
      id: '/_auth/shops/$shopId/edit/'
      path: '/shops/$shopId/edit'
      fullPath: '/shops/$shopId/edit'
      preLoaderRoute: typeof AuthShopsShopIdEditIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shops/$shopId/staffs/$staffId/': {
      id: '/_auth/shops/$shopId/staffs/$staffId/'
      path: '/shops/$shopId/staffs/$staffId'
      fullPath: '/shops/$shopId/staffs/$staffId'
      preLoaderRoute: typeof AuthShopsShopIdStaffsStaffIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shops/$shopId/staffs/$staffId/edit': {
      id: '/_auth/shops/$shopId/staffs/$staffId/edit'
      path: '/shops/$shopId/staffs/$staffId/edit'
      fullPath: '/shops/$shopId/staffs/$staffId/edit'
      preLoaderRoute: typeof AuthShopsShopIdStaffsStaffIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMypageRoute: typeof AuthMypageRoute
  AuthShiftsRoute: typeof AuthShiftsRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthShopsIndexRoute: typeof AuthShopsIndexRoute
  AuthSettingsShiftTemplateAddRoute: typeof AuthSettingsShiftTemplateAddRoute
  AuthSettingsShiftTemplateEditRoute: typeof AuthSettingsShiftTemplateEditRoute
  AuthSettingsShiftTemplateIndexRoute: typeof AuthSettingsShiftTemplateIndexRoute
  AuthShopsShopIdIndexRoute: typeof AuthShopsShopIdIndexRoute
  AuthShopsNewIndexRoute: typeof AuthShopsNewIndexRoute
  AuthShopsShopIdEditIndexRoute: typeof AuthShopsShopIdEditIndexRoute
  AuthShopsShopIdStaffsStaffIdEditRoute: typeof AuthShopsShopIdStaffsStaffIdEditRoute
  AuthShopsShopIdStaffsStaffIdIndexRoute: typeof AuthShopsShopIdStaffsStaffIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMypageRoute: AuthMypageRoute,
  AuthShiftsRoute: AuthShiftsRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthShopsIndexRoute: AuthShopsIndexRoute,
  AuthSettingsShiftTemplateAddRoute: AuthSettingsShiftTemplateAddRoute,
  AuthSettingsShiftTemplateEditRoute: AuthSettingsShiftTemplateEditRoute,
  AuthSettingsShiftTemplateIndexRoute: AuthSettingsShiftTemplateIndexRoute,
  AuthShopsShopIdIndexRoute: AuthShopsShopIdIndexRoute,
  AuthShopsNewIndexRoute: AuthShopsNewIndexRoute,
  AuthShopsShopIdEditIndexRoute: AuthShopsShopIdEditIndexRoute,
  AuthShopsShopIdStaffsStaffIdEditRoute: AuthShopsShopIdStaffsStaffIdEditRoute,
  AuthShopsShopIdStaffsStaffIdIndexRoute:
    AuthShopsShopIdStaffsStaffIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UnregisteredRouteChildren {
  UnregisteredWelcomeRoute: typeof UnregisteredWelcomeRoute
}

const UnregisteredRouteChildren: UnregisteredRouteChildren = {
  UnregisteredWelcomeRoute: UnregisteredWelcomeRoute,
}

const UnregisteredRouteWithChildren = UnregisteredRoute._addFileChildren(
  UnregisteredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  AuthRoute: AuthRouteWithChildren,
  UnregisteredRoute: UnregisteredRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
