/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as UnregisteredRouteImport } from './routes/_unregistered'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsStaffRouteImport } from './routes/terms.staff'
import { Route as TermsManagerRouteImport } from './routes/terms.manager'
import { Route as PrivacyStaffRouteImport } from './routes/privacy.staff'
import { Route as PrivacyManagerRouteImport } from './routes/privacy.manager'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as UnregisteredShiftsViewRouteImport } from './routes/_unregistered/shifts.view'
import { Route as UnregisteredShiftsSubmitRouteImport } from './routes/_unregistered/shifts.submit'
import { Route as UnregisteredShiftsReissueRouteImport } from './routes/_unregistered/shifts.reissue'
import { Route as UnregisteredLineCallbackRouteImport } from './routes/_unregistered/line.callback'
import { Route as UnregisteredDemoShiftboardRouteImport } from './routes/_unregistered/demo.shiftboard'
import { Route as AuthShiftboardRecruitmentIdRouteImport } from './routes/_auth/shiftboard.$recruitmentId'
import { Route as UnregisteredShiftsSubmitCompletedRouteImport } from './routes/_unregistered/shifts.submit_.completed'
import { Route as UnregisteredLegalStaffConsentRouteImport } from './routes/_unregistered/legal.staff.consent'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const UnregisteredRoute = UnregisteredRouteImport.update({
  id: '/_unregistered',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsStaffRoute = TermsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => TermsRoute,
} as any)
const TermsManagerRoute = TermsManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => TermsRoute,
} as any)
const PrivacyStaffRoute = PrivacyStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PrivacyRoute,
} as any)
const PrivacyManagerRoute = PrivacyManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => PrivacyRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const UnregisteredShiftsViewRoute = UnregisteredShiftsViewRouteImport.update({
  id: '/shifts/view',
  path: '/shifts/view',
  getParentRoute: () => UnregisteredRoute,
} as any)
const UnregisteredShiftsSubmitRoute =
  UnregisteredShiftsSubmitRouteImport.update({
    id: '/shifts/submit',
    path: '/shifts/submit',
    getParentRoute: () => UnregisteredRoute,
  } as any)
const UnregisteredShiftsReissueRoute =
  UnregisteredShiftsReissueRouteImport.update({
    id: '/shifts/reissue',
    path: '/shifts/reissue',
    getParentRoute: () => UnregisteredRoute,
  } as any)
const UnregisteredLineCallbackRoute =
  UnregisteredLineCallbackRouteImport.update({
    id: '/line/callback',
    path: '/line/callback',
    getParentRoute: () => UnregisteredRoute,
  } as any)
const UnregisteredDemoShiftboardRoute =
  UnregisteredDemoShiftboardRouteImport.update({
    id: '/demo/shiftboard',
    path: '/demo/shiftboard',
    getParentRoute: () => UnregisteredRoute,
  } as any)
const AuthShiftboardRecruitmentIdRoute =
  AuthShiftboardRecruitmentIdRouteImport.update({
    id: '/shiftboard/$recruitmentId',
    path: '/shiftboard/$recruitmentId',
    getParentRoute: () => AuthRoute,
  } as any)
const UnregisteredShiftsSubmitCompletedRoute =
  UnregisteredShiftsSubmitCompletedRouteImport.update({
    id: '/shifts/submit_/completed',
    path: '/shifts/submit/completed',
    getParentRoute: () => UnregisteredRoute,
  } as any)
const UnregisteredLegalStaffConsentRoute =
  UnregisteredLegalStaffConsentRouteImport.update({
    id: '/legal/staff/consent',
    path: '/legal/staff/consent',
    getParentRoute: () => UnregisteredRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/terms': typeof TermsRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/privacy/manager': typeof PrivacyManagerRoute
  '/privacy/staff': typeof PrivacyStaffRoute
  '/terms/manager': typeof TermsManagerRoute
  '/terms/staff': typeof TermsStaffRoute
  '/shiftboard/$recruitmentId': typeof AuthShiftboardRecruitmentIdRoute
  '/demo/shiftboard': typeof UnregisteredDemoShiftboardRoute
  '/line/callback': typeof UnregisteredLineCallbackRoute
  '/shifts/reissue': typeof UnregisteredShiftsReissueRoute
  '/shifts/submit': typeof UnregisteredShiftsSubmitRoute
  '/shifts/view': typeof UnregisteredShiftsViewRoute
  '/legal/staff/consent': typeof UnregisteredLegalStaffConsentRoute
  '/shifts/submit/completed': typeof UnregisteredShiftsSubmitCompletedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/terms': typeof TermsRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/privacy/manager': typeof PrivacyManagerRoute
  '/privacy/staff': typeof PrivacyStaffRoute
  '/terms/manager': typeof TermsManagerRoute
  '/terms/staff': typeof TermsStaffRoute
  '/shiftboard/$recruitmentId': typeof AuthShiftboardRecruitmentIdRoute
  '/demo/shiftboard': typeof UnregisteredDemoShiftboardRoute
  '/line/callback': typeof UnregisteredLineCallbackRoute
  '/shifts/reissue': typeof UnregisteredShiftsReissueRoute
  '/shifts/submit': typeof UnregisteredShiftsSubmitRoute
  '/shifts/view': typeof UnregisteredShiftsViewRoute
  '/legal/staff/consent': typeof UnregisteredLegalStaffConsentRoute
  '/shifts/submit/completed': typeof UnregisteredShiftsSubmitCompletedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_unregistered': typeof UnregisteredRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/terms': typeof TermsRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/privacy/manager': typeof PrivacyManagerRoute
  '/privacy/staff': typeof PrivacyStaffRoute
  '/terms/manager': typeof TermsManagerRoute
  '/terms/staff': typeof TermsStaffRoute
  '/_auth/shiftboard/$recruitmentId': typeof AuthShiftboardRecruitmentIdRoute
  '/_unregistered/demo/shiftboard': typeof UnregisteredDemoShiftboardRoute
  '/_unregistered/line/callback': typeof UnregisteredLineCallbackRoute
  '/_unregistered/shifts/reissue': typeof UnregisteredShiftsReissueRoute
  '/_unregistered/shifts/submit': typeof UnregisteredShiftsSubmitRoute
  '/_unregistered/shifts/view': typeof UnregisteredShiftsViewRoute
  '/_unregistered/legal/staff/consent': typeof UnregisteredLegalStaffConsentRoute
  '/_unregistered/shifts/submit_/completed': typeof UnregisteredShiftsSubmitCompletedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/privacy/manager'
    | '/privacy/staff'
    | '/terms/manager'
    | '/terms/staff'
    | '/shiftboard/$recruitmentId'
    | '/demo/shiftboard'
    | '/line/callback'
    | '/shifts/reissue'
    | '/shifts/submit'
    | '/shifts/view'
    | '/legal/staff/consent'
    | '/shifts/submit/completed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/privacy/manager'
    | '/privacy/staff'
    | '/terms/manager'
    | '/terms/staff'
    | '/shiftboard/$recruitmentId'
    | '/demo/shiftboard'
    | '/line/callback'
    | '/shifts/reissue'
    | '/shifts/submit'
    | '/shifts/view'
    | '/legal/staff/consent'
    | '/shifts/submit/completed'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_unregistered'
    | '/privacy'
    | '/terms'
    | '/_auth/dashboard'
    | '/privacy/manager'
    | '/privacy/staff'
    | '/terms/manager'
    | '/terms/staff'
    | '/_auth/shiftboard/$recruitmentId'
    | '/_unregistered/demo/shiftboard'
    | '/_unregistered/line/callback'
    | '/_unregistered/shifts/reissue'
    | '/_unregistered/shifts/submit'
    | '/_unregistered/shifts/view'
    | '/_unregistered/legal/staff/consent'
    | '/_unregistered/shifts/submit_/completed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UnregisteredRoute: typeof UnregisteredRouteWithChildren
  PrivacyRoute: typeof PrivacyRouteWithChildren
  TermsRoute: typeof TermsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unregistered': {
      id: '/_unregistered'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnregisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/staff': {
      id: '/terms/staff'
      path: '/staff'
      fullPath: '/terms/staff'
      preLoaderRoute: typeof TermsStaffRouteImport
      parentRoute: typeof TermsRoute
    }
    '/terms/manager': {
      id: '/terms/manager'
      path: '/manager'
      fullPath: '/terms/manager'
      preLoaderRoute: typeof TermsManagerRouteImport
      parentRoute: typeof TermsRoute
    }
    '/privacy/staff': {
      id: '/privacy/staff'
      path: '/staff'
      fullPath: '/privacy/staff'
      preLoaderRoute: typeof PrivacyStaffRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/privacy/manager': {
      id: '/privacy/manager'
      path: '/manager'
      fullPath: '/privacy/manager'
      preLoaderRoute: typeof PrivacyManagerRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_unregistered/shifts/view': {
      id: '/_unregistered/shifts/view'
      path: '/shifts/view'
      fullPath: '/shifts/view'
      preLoaderRoute: typeof UnregisteredShiftsViewRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_unregistered/shifts/submit': {
      id: '/_unregistered/shifts/submit'
      path: '/shifts/submit'
      fullPath: '/shifts/submit'
      preLoaderRoute: typeof UnregisteredShiftsSubmitRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_unregistered/shifts/reissue': {
      id: '/_unregistered/shifts/reissue'
      path: '/shifts/reissue'
      fullPath: '/shifts/reissue'
      preLoaderRoute: typeof UnregisteredShiftsReissueRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_unregistered/line/callback': {
      id: '/_unregistered/line/callback'
      path: '/line/callback'
      fullPath: '/line/callback'
      preLoaderRoute: typeof UnregisteredLineCallbackRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_unregistered/demo/shiftboard': {
      id: '/_unregistered/demo/shiftboard'
      path: '/demo/shiftboard'
      fullPath: '/demo/shiftboard'
      preLoaderRoute: typeof UnregisteredDemoShiftboardRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_auth/shiftboard/$recruitmentId': {
      id: '/_auth/shiftboard/$recruitmentId'
      path: '/shiftboard/$recruitmentId'
      fullPath: '/shiftboard/$recruitmentId'
      preLoaderRoute: typeof AuthShiftboardRecruitmentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_unregistered/shifts/submit_/completed': {
      id: '/_unregistered/shifts/submit_/completed'
      path: '/shifts/submit/completed'
      fullPath: '/shifts/submit/completed'
      preLoaderRoute: typeof UnregisteredShiftsSubmitCompletedRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_unregistered/legal/staff/consent': {
      id: '/_unregistered/legal/staff/consent'
      path: '/legal/staff/consent'
      fullPath: '/legal/staff/consent'
      preLoaderRoute: typeof UnregisteredLegalStaffConsentRouteImport
      parentRoute: typeof UnregisteredRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthShiftboardRecruitmentIdRoute: typeof AuthShiftboardRecruitmentIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthShiftboardRecruitmentIdRoute: AuthShiftboardRecruitmentIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UnregisteredRouteChildren {
  UnregisteredDemoShiftboardRoute: typeof UnregisteredDemoShiftboardRoute
  UnregisteredLineCallbackRoute: typeof UnregisteredLineCallbackRoute
  UnregisteredShiftsReissueRoute: typeof UnregisteredShiftsReissueRoute
  UnregisteredShiftsSubmitRoute: typeof UnregisteredShiftsSubmitRoute
  UnregisteredShiftsViewRoute: typeof UnregisteredShiftsViewRoute
  UnregisteredLegalStaffConsentRoute: typeof UnregisteredLegalStaffConsentRoute
  UnregisteredShiftsSubmitCompletedRoute: typeof UnregisteredShiftsSubmitCompletedRoute
}

const UnregisteredRouteChildren: UnregisteredRouteChildren = {
  UnregisteredDemoShiftboardRoute: UnregisteredDemoShiftboardRoute,
  UnregisteredLineCallbackRoute: UnregisteredLineCallbackRoute,
  UnregisteredShiftsReissueRoute: UnregisteredShiftsReissueRoute,
  UnregisteredShiftsSubmitRoute: UnregisteredShiftsSubmitRoute,
  UnregisteredShiftsViewRoute: UnregisteredShiftsViewRoute,
  UnregisteredLegalStaffConsentRoute: UnregisteredLegalStaffConsentRoute,
  UnregisteredShiftsSubmitCompletedRoute:
    UnregisteredShiftsSubmitCompletedRoute,
}

const UnregisteredRouteWithChildren = UnregisteredRoute._addFileChildren(
  UnregisteredRouteChildren,
)

interface PrivacyRouteChildren {
  PrivacyManagerRoute: typeof PrivacyManagerRoute
  PrivacyStaffRoute: typeof PrivacyStaffRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacyManagerRoute: PrivacyManagerRoute,
  PrivacyStaffRoute: PrivacyStaffRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

interface TermsRouteChildren {
  TermsManagerRoute: typeof TermsManagerRoute
  TermsStaffRoute: typeof TermsStaffRoute
}

const TermsRouteChildren: TermsRouteChildren = {
  TermsManagerRoute: TermsManagerRoute,
  TermsStaffRoute: TermsStaffRoute,
}

const TermsRouteWithChildren = TermsRoute._addFileChildren(TermsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UnregisteredRoute: UnregisteredRouteWithChildren,
  PrivacyRoute: PrivacyRouteWithChildren,
  TermsRoute: TermsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
