/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnregisteredRouteImport } from './routes/_unregistered'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnregisteredWelcomeRouteImport } from './routes/_unregistered/welcome'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthShiftboardRecruitmentIdRouteImport } from './routes/_auth/shiftboard.$recruitmentId'

const UnregisteredRoute = UnregisteredRouteImport.update({
  id: '/_unregistered',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnregisteredWelcomeRoute = UnregisteredWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => UnregisteredRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthShiftboardRecruitmentIdRoute =
  AuthShiftboardRecruitmentIdRouteImport.update({
    id: '/shiftboard/$recruitmentId',
    path: '/shiftboard/$recruitmentId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/welcome': typeof UnregisteredWelcomeRoute
  '/shiftboard/$recruitmentId': typeof AuthShiftboardRecruitmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/welcome': typeof UnregisteredWelcomeRoute
  '/shiftboard/$recruitmentId': typeof AuthShiftboardRecruitmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_unregistered': typeof UnregisteredRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_unregistered/welcome': typeof UnregisteredWelcomeRoute
  '/_auth/shiftboard/$recruitmentId': typeof AuthShiftboardRecruitmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/welcome' | '/shiftboard/$recruitmentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/welcome' | '/shiftboard/$recruitmentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_unregistered'
    | '/_auth/dashboard'
    | '/_unregistered/welcome'
    | '/_auth/shiftboard/$recruitmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UnregisteredRoute: typeof UnregisteredRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unregistered': {
      id: '/_unregistered'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnregisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unregistered/welcome': {
      id: '/_unregistered/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof UnregisteredWelcomeRouteImport
      parentRoute: typeof UnregisteredRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shiftboard/$recruitmentId': {
      id: '/_auth/shiftboard/$recruitmentId'
      path: '/shiftboard/$recruitmentId'
      fullPath: '/shiftboard/$recruitmentId'
      preLoaderRoute: typeof AuthShiftboardRecruitmentIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthShiftboardRecruitmentIdRoute: typeof AuthShiftboardRecruitmentIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthShiftboardRecruitmentIdRoute: AuthShiftboardRecruitmentIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UnregisteredRouteChildren {
  UnregisteredWelcomeRoute: typeof UnregisteredWelcomeRoute
}

const UnregisteredRouteChildren: UnregisteredRouteChildren = {
  UnregisteredWelcomeRoute: UnregisteredWelcomeRoute,
}

const UnregisteredRouteWithChildren = UnregisteredRoute._addFileChildren(
  UnregisteredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UnregisteredRoute: UnregisteredRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
