name: Playwright setup from cache
description: Playwright setup from cache

runs:
  using: "composite"
  steps:
    - name: Setup Playwright cache
      id: playwright-cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: /home/runner/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-chromium-cache-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-playwright-chromium-cache-
    - name: Install Playwright Chromium
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install chromium
    - name: Install Playwright Chromium OS dependencies
      shell: bash
      run: npx playwright install-deps chromium
