name: chromatic_pr_on_push

on: pull_request

jobs:
  chromatic_pr_on_push:
    if: (github.event.pull_request.draft == false && !contains(github.head_ref, 'renovate/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # Chromatic ActionはNode20で動いてそう・・・？
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: pnpm
        shell: bash
        run: corepack enable
      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
