name: chromatic_on_merge_to_develop

on:
  push:
    branches: [develop]

jobs:
  chromatic_on_merge_to_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # Chromatic ActionはNode20で動いてそう・・・？
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: pnpm
        shell: bash
        run: corepack enable
      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          autoAcceptChanges: true
