name: chromatic_pr_on_ready

on:
  pull_request:
    types: [ready_for_review]

jobs:
  chromatic_pr_on_ready:
    if: (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name , 'renovate'))
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Storybook Build  
        run: pnpm storybook:build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
