name: Playwright Tests

on:
    pull_request:
      branches: [develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup
      uses: ./.github/actions/setup
    - name: Setup Playwright
      uses: ./.github/actions/playwright
    - name: Run Playwright tests
      run: pnpm e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
