name: Playwright Tests

on:
  pull_request:
    branches: [develop]

concurrency:
  group: e2e-tests-global
  cancel-in-progress: false

jobs:
  e2e:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: preview
    steps: 
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Setup
      uses: ./.github/actions/setup
    - name: Dev Database Reset
      uses: ./.github/actions/dev-database
      with:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
        TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
        TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
    - name: Setup Playwright
      uses: ./.github/actions/playwright
      with:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
        TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
        TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
    - name: Playwright test
      run: pnpm e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  upload-to-github-pages:
    needs: e2e
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: gh-pages
      - name: Download Playwright Report Artifact
        uses: actions/download-artifact@v5
        with:
          name: playwright-report
          path: "./playwright/${{ github.ref_name }}"
      - name: Commit and push changes with retry
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add playwright
          git commit -m "chore: Update Playwright report in ${{ github.ref_name }}"
          
          # リトライロジック - 最大5回まで試行
          for i in {1..5}; do
            if git push; then
              echo "Successfully pushed on attempt $i"
              break
            else
              if [ $i -eq 5 ]; then
                echo "Failed to push after 5 attempts"
                exit 1
              fi
              echo "Push failed on attempt $i, retrying..."
              sleep 5
              git pull --rebase origin gh-pages
            fi
          done
      - name: Create comments
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message-id: playwright
          message: |
            🎭 Playwright Test Report 🎭
            [Playwright Report](https://yn1323.github.io/yps-polar/playwright/${{ github.ref_name }})
