name: pxdiff_on_merge_to_develop

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  checks: write

jobs:
  pxdiff_on_merge_to_develop:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Storybook Build
        run: pnpm vrt:build
      - name: Capture VRT screenshots
        run: pnpm vrt:capture
      - name: Upload and approve screenshots in pxdiff
        id: pxdiff
        run: pnpm vrt:upload
        env:
          PXDIFF_API_KEY: ${{ secrets.PXDIFF_API_KEY }}
          PXDIFF_AUTO_APPROVE: "true"
          PXDIFF_SUITE: storybook-poc
