name: test-convex-logic

on:
  - push

jobs:
  convex-logic-test:
    name: convex-logic-test (${{ matrix.shard }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/2, 2/2]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Test
        run: pnpm vitest run --shard=${{ matrix.shard }} --project='convex(logic)'
