name: test-ui

on:
  - push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/2, 2/2]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Execute Convex
        run: pnpm convex:dev
      - name: Setup Playwright
        uses: ./.github/actions/playwright
      - name: Run Test
        run: |
          npx convex dev &        
          sleep 5
          pnpm vitest run --shard=${{ matrix.shard }} --project=ui
          kill %1
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY : ${{ secrets.CLERK_PUBLISHABLE_KEY }}
