name: test-ui

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  unit-test:
    name: ui-test (${{ matrix.shard }})
    runs-on: ubuntu-latest
    env:
      VITE_CLERK_PUBLISHABLE_KEY: pk_test_storybook
      VITE_CONVEX_URL: https://storybook.convex.cloud
    strategy:
      fail-fast: false
      matrix:
        shard: [1/2, 2/2]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
          persist-credentials: false
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup Playwright
        uses: ./.github/actions/playwright
      - name: Run Test
        run: pnpm vitest run --shard=${{ matrix.shard }} --project=ui
