name: type-check

on:
  - push

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Type Check
        run: pnpm type-check
